//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public Assessment()
        {
            this.Marks = new HashSet<Mark>();
            this.Subjects = new HashSet<Subject>();
            this.Subjects1 = new HashSet<Subject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Inactive { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Mark> Marks { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<Subject> Subjects1 { get; set; }
    }
}
