//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksRead
    {
        public int BooksRead_Id { get; set; }
        public int Student_Id { get; set; }
        public string ForYear { get; set; }
        public int BooksRead1 { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
