//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardAddress
    {
        public CardAddress()
        {
            this.Parents = new HashSet<Parent>();
            this.Students = new HashSet<Student>();
        }
    
        public int Address_Id { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Town { get; set; }
        public string CountryCode { get; set; }
        public string StateName { get; set; }
        public string Postcode { get; set; }
        public Nullable<int> Country_Id { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Parent> Parents { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
