//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Classes_Id { get; set; }
        public string ClassDesc { get; set; }
        public string Year { get; set; }
        public Nullable<int> Teacher_Id { get; set; }
        public string Stage { get; set; }
        public bool Obsolete { get; set; }
        public int Library_Id { get; set; }
        public Nullable<int> Old_Id { get; set; }
        public Nullable<int> Teacher2Id { get; set; }
    
        public virtual Library Library { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Teacher Teacher1 { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
