//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactTitle
    {
        public ContactTitle()
        {
            this.Parents = new HashSet<Parent>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int Title_Id { get; set; }
        public string Salutation { get; set; }
    
        public virtual ICollection<Parent> Parents { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
