//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.CardAddresses = new HashSet<CardAddress>();
        }
    
        public int Country_Id { get; set; }
        public string Country1 { get; set; }
        public string CountryCode { get; set; }
        public string PostalZone { get; set; }
        public bool DontUse { get; set; }
        public string MarcCode { get; set; }
    
        public virtual ICollection<CardAddress> CardAddresses { get; set; }
    }
}
