//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CsvList
    {
        public int CsvList_Id { get; set; }
        public string ListName { get; set; }
        public string FieldList { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public Nullable<int> Library_Id { get; set; }
    
        public virtual Library Library { get; set; }
    }
}
