//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeReport
    {
        public GradeReport()
        {
            this.Subjects = new HashSet<Subject>();
        }
    
        public int Id { get; set; }
        public int SchoolReportId { get; set; }
        public int GradeId { get; set; }
        public bool Ready { get; set; }
        public string Supervisor { get; set; }
        public string Position { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ReportSchool ReportSchool { get; set; }
    }
}
