//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeReadingEntities : DbContext
    {
        public HomeReadingEntities()
            : base("name=HomeReadingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annotation> Annotations { get; set; }
        public virtual DbSet<CardAddress> CardAddresses { get; set; }
        public virtual DbSet<ContactTitle> ContactTitles { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CsvList> CsvLists { get; set; }
        public virtual DbSet<ImportData> ImportDatas { get; set; }
        public virtual DbSet<ImportMap> ImportMaps { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<LibImage> LibImages { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<OnixAuthorRole> OnixAuthorRoles { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<ProdAuthor> ProdAuthors { get; set; }
        public virtual DbSet<ProdAvailability> ProdAvailabilities { get; set; }
        public virtual DbSet<ProdImage> ProdImages { get; set; }
        public virtual DbSet<ProdStock> ProdStocks { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<STCount> STCounts { get; set; }
        public virtual DbSet<StSession> StSessions { get; set; }
        public virtual DbSet<StudentContact> StudentContacts { get; set; }
        public virtual DbSet<SystemVar> SystemVars { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<GradeReport> GradeReports { get; set; }
        public virtual DbSet<ReportStudent> ReportStudents { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<PrintLabel> PrintLabels { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<UserSetting> UserSettings { get; set; }
        public virtual DbSet<ImportFile> ImportFiles { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<DefaultKla> DefaultKlas { get; set; }
        public virtual DbSet<BooksRead> BooksReads { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<ReportSchool> ReportSchools { get; set; }
    }
}
