//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportFile
    {
        public ImportFile()
        {
            this.ImportDatas = new HashSet<ImportData>();
            this.ImportMaps = new HashSet<ImportMap>();
        }
    
        public int ImportFile_Id { get; set; }
        public System.DateTime Entered { get; set; }
        public Nullable<int> ImportType { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<ImportData> ImportDatas { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<ImportMap> ImportMaps { get; set; }
    }
}
