//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public Level()
        {
            this.Products = new HashSet<Product>();
            this.Students = new HashSet<Student>();
        }
    
        public int Levels_Id { get; set; }
        public string ReadLevel { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Obsolete { get; set; }
        public string FP { get; set; }
        public string ReadAge { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
