//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public Library()
        {
            this.CsvLists = new HashSet<CsvList>();
            this.Parents = new HashSet<Parent>();
            this.ProdStocks = new HashSet<ProdStock>();
            this.StSessions = new HashSet<StSession>();
            this.Classes = new HashSet<Class>();
            this.PrintLabels = new HashSet<PrintLabel>();
            this.Products = new HashSet<Product>();
            this.Teachers = new HashSet<Teacher>();
            this.Students = new HashSet<Student>();
            this.ReportSchools = new HashSet<ReportSchool>();
        }
    
        public int Library_Id { get; set; }
        public string Licensee { get; set; }
        public string LicAdd1 { get; set; }
        public string LicAdd2 { get; set; }
        public string LicTown { get; set; }
        public string LicPostCode { get; set; }
        public string LicPhone { get; set; }
        public string LicFax { get; set; }
        public string LicEmail { get; set; }
        public Nullable<bool> StocktakeFlag { get; set; }
        public Nullable<System.DateTime> StocktakeDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> LicType { get; set; }
        public Nullable<System.DateTime> LastSTDate { get; set; }
        public string StLetter1 { get; set; }
        public string StLetter2 { get; set; }
        public string StLetterName { get; set; }
        public string StLetterPosition { get; set; }
        public string StLetterSize { get; set; }
    
        public virtual ICollection<CsvList> CsvLists { get; set; }
        public virtual ICollection<Parent> Parents { get; set; }
        public virtual ICollection<ProdStock> ProdStocks { get; set; }
        public virtual ICollection<StSession> StSessions { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<PrintLabel> PrintLabels { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<ReportSchool> ReportSchools { get; set; }
    }
}
