//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public Mark()
        {
            this.Results = new HashSet<Result>();
            this.Results1 = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AssessmentId { get; set; }
        public short ColOrder { get; set; }
        public string Description { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<Result> Results1 { get; set; }
    }
}
