//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnixAuthorRole
    {
        public OnixAuthorRole()
        {
            this.ProdAuthors = new HashSet<ProdAuthor>();
        }
    
        public int Role_Id { get; set; }
        public string RoleCode { get; set; }
        public string Role { get; set; }
        public string Description { get; set; }
        public string Abbreviation { get; set; }
        public string Bowker { get; set; }
        public string Done { get; set; }
    
        public virtual ICollection<ProdAuthor> ProdAuthors { get; set; }
    }
}
