//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.StudentContacts = new HashSet<StudentContact>();
        }
    
        public int Parent_Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> Title_Id { get; set; }
        public Nullable<int> Address_Id { get; set; }
        public string Phone2 { get; set; }
        public Nullable<int> Library_Id { get; set; }
        public Nullable<int> Old_Id { get; set; }
    
        public virtual CardAddress CardAddress { get; set; }
        public virtual ContactTitle ContactTitle { get; set; }
        public virtual Library Library { get; set; }
        public virtual ICollection<StudentContact> StudentContacts { get; set; }
    }
}
