//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdAuthor
    {
        public int Author_Id { get; set; }
        public int Product_Id { get; set; }
        public string Author { get; set; }
        public int Role_Id { get; set; }
    
        public virtual OnixAuthorRole OnixAuthorRole { get; set; }
        public virtual Product Product { get; set; }
    }
}
