//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdAvailability
    {
        public ProdAvailability()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Availability_Id { get; set; }
        public string OnixCode { get; set; }
        public string Translated { get; set; }
        public string Availability { get; set; }
        public string Description { get; set; }
        public string OOSReason { get; set; }
        public string Bowker { get; set; }
        public Nullable<bool> NoSales { get; set; }
        public Nullable<bool> NoBackOrders { get; set; }
        public Nullable<bool> NoWeb { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Deprecated { get; set; }
        public Nullable<bool> OperatorSet { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
