//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Annotations = new HashSet<Annotation>();
            this.Loans = new HashSet<Loan>();
            this.PrintLabels = new HashSet<PrintLabel>();
            this.ProdAuthors = new HashSet<ProdAuthor>();
            this.ProdImages = new HashSet<ProdImage>();
            this.ProdStocks = new HashSet<ProdStock>();
            this.STCounts = new HashSet<STCount>();
        }
    
        public int Product_Id { get; set; }
        public string Isbn { get; set; }
        public string Catalog { get; set; }
        public string Title { get; set; }
        public Nullable<int> Imprint_Id { get; set; }
        public Nullable<int> Availability_Id { get; set; }
        public Nullable<int> Format_Id { get; set; }
        public Nullable<decimal> Retail { get; set; }
        public Nullable<decimal> AvrCost { get; set; }
        public Nullable<bool> NoStkControl { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Entered { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string OldIsbn { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> Levels_Id { get; set; }
        public Nullable<bool> Authorised { get; set; }
        public Nullable<int> Library_Id { get; set; }
        public Nullable<int> Old_Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ICollection<Annotation> Annotations { get; set; }
        public virtual Level Level { get; set; }
        public virtual Library Library { get; set; }
        public virtual ICollection<Loan> Loans { get; set; }
        public virtual ICollection<PrintLabel> PrintLabels { get; set; }
        public virtual ICollection<ProdAuthor> ProdAuthors { get; set; }
        public virtual ProdAvailability ProdAvailability { get; set; }
        public virtual ICollection<ProdImage> ProdImages { get; set; }
        public virtual ICollection<ProdStock> ProdStocks { get; set; }
        public virtual ICollection<STCount> STCounts { get; set; }
    }
}
