//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public Relationship()
        {
            this.StudentContacts = new HashSet<StudentContact>();
        }
    
        public int Relation_Id { get; set; }
        public string Relationship1 { get; set; }
    
        public virtual ICollection<StudentContact> StudentContacts { get; set; }
    }
}
