//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportStudent
    {
        public ReportStudent()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public int SchoolReportId { get; set; }
        public int StudentId { get; set; }
        public string Comments { get; set; }
        public string SuperComments { get; set; }
        public int AbsentFull { get; set; }
        public int AbsentPart { get; set; }
        public Nullable<System.DateTime> AbsentDate { get; set; }
        public string Teacher { get; set; }
        public string Teacher2 { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Result> Results { get; set; }
        public virtual Teacher Teacher1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual ReportSchool ReportSchool { get; set; }
    }
}
