//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STCount
    {
        public int STCount_Id { get; set; }
        public int StSessions_Id { get; set; }
        public int Product_Id { get; set; }
        public int Qty { get; set; }
        public string Barcode { get; set; }
        public System.DateTime CountDate { get; set; }
    
        public virtual StSession StSession { get; set; }
        public virtual Product Product { get; set; }
    }
}
