//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Loans = new HashSet<Loan>();
            this.ReportStudents = new HashSet<ReportStudent>();
            this.StudentContacts = new HashSet<StudentContact>();
            this.BooksReads = new HashSet<BooksRead>();
        }
    
        public int Student_Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string KnownAs { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<int> Classes_Id { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Levels_Id { get; set; }
        public Nullable<int> Address_Id { get; set; }
        public int Library_id { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Old_Id { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string SRN { get; set; }
    
        public virtual CardAddress CardAddress { get; set; }
        public virtual Class Class { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Level Level { get; set; }
        public virtual Library Library { get; set; }
        public virtual ICollection<Loan> Loans { get; set; }
        public virtual ICollection<ReportStudent> ReportStudents { get; set; }
        public virtual ICollection<StudentContact> StudentContacts { get; set; }
        public virtual ICollection<BooksRead> BooksReads { get; set; }
    }
}
