//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Results = new HashSet<Result>();
            this.Subjects1 = new HashSet<Subject>();
        }
    
        public int Id { get; set; }
        public int GradeReportId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int AssessmentId { get; set; }
        public int EffortId { get; set; }
        public bool Inactive { get; set; }
        public int ReportType { get; set; }
        public int ColOrder { get; set; }
        public bool IsTopic { get; set; }
        public Nullable<int> OldId { get; set; }
        public bool PageBreak { get; set; }
        public bool KlaComments { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual Assessment Assessment1 { get; set; }
        public virtual GradeReport GradeReport { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<Subject> Subjects1 { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
