//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemVar
    {
        public int SysVars_Id { get; set; }
        public string TPLogin { get; set; }
        public string TPPassword { get; set; }
        public string NBLogin { get; set; }
        public string NBPassword { get; set; }
        public string BoLogin { get; set; }
        public string BoPassword { get; set; }
        public string NextIsbn { get; set; }
        public Nullable<int> TotalUsers { get; set; }
        public Nullable<int> TotalGuests { get; set; }
    }
}
