//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Classes = new HashSet<Class>();
            this.Classes1 = new HashSet<Class>();
            this.PrintLabels = new HashSet<PrintLabel>();
            this.ReportStudents = new HashSet<ReportStudent>();
            this.UserSettings = new HashSet<UserSetting>();
            this.ImportFiles = new HashSet<ImportFile>();
        }
    
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int Teacher_Id { get; set; }
        public bool Inactive { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public int Library_Id { get; set; }
        public Nullable<int> Title_Id { get; set; }
        public string UserName { get; set; }
        public int Role { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<Class> Classes1 { get; set; }
        public virtual ContactTitle ContactTitle { get; set; }
        public virtual Library Library { get; set; }
        public virtual ICollection<PrintLabel> PrintLabels { get; set; }
        public virtual ICollection<ReportStudent> ReportStudents { get; set; }
        public virtual ICollection<UserSetting> UserSettings { get; set; }
        public virtual ICollection<ImportFile> ImportFiles { get; set; }
    }
}
