//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeReadingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int UserSettings_Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> LabelsPerCol { get; set; }
        public Nullable<int> ColsPerPage { get; set; }
        public Nullable<int> LabelsTop { get; set; }
        public Nullable<int> LabelsBottom { get; set; }
        public Nullable<int> LabelsLeft { get; set; }
        public Nullable<int> LabelsRight { get; set; }
        public int UserId { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
